
name: CI-CD

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Checkout and build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download & Update sudo
        run: |
          sudo apt update && sudo apt install -y sudo
      - name: Install Docker
        run: |
          curl -sSL https://get.docker.com/ | sudo sh
      - name: Build Docker image
        working-directory: .
        run: |
          ls -l
          docker build -f emotionsapi/Dockerfile . -t emotionsapi
